// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'kiroku.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class KirokuAdapter extends TypeAdapter<Kiroku> {
  @override
  final int typeId = 3;

  @override
  Kiroku read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Kiroku()
      ..time_zentai_ryuugakusei_kukankiroku = (fields[0] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<double>())
              .toList())
          .toList()
      ..year_zentai_ryuugakusei_kukankiroku = (fields[1] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..month_zentai_ryuugakusei_kukankiroku = (fields[2] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..univname_zentai_ryuugakusei_kukankiroku = (fields[3] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..name_zentai_ryuugakusei_kukankiroku = (fields[4] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..gakunen_zentai_ryuugakusei_kukankiroku = (fields[5] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..time_zentai_ryuugakusei_kojinkiroku = (fields[6] as List)
          .map((dynamic e) => (e as List).cast<double>())
          .toList()
      ..year_zentai_ryuugakusei_kojinkiroku = (fields[7] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..month_zentai_ryuugakusei_kojinkiroku = (fields[8] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..univname_zentai_ryuugakusei_kojinkiroku = (fields[9] as List)
          .map((dynamic e) => (e as List).cast<String>())
          .toList()
      ..name_zentai_ryuugakusei_kojinkiroku = (fields[10] as List)
          .map((dynamic e) => (e as List).cast<String>())
          .toList()
      ..gakunen_zentai_ryuugakusei_kojinkiroku = (fields[11] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..time_zentai_jap_kukankiroku = (fields[12] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<double>())
              .toList())
          .toList()
      ..year_zentai_jap_kukankiroku = (fields[13] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..month_zentai_jap_kukankiroku = (fields[14] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..univname_zentai_jap_kukankiroku = (fields[15] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..name_zentai_jap_kukankiroku = (fields[16] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..gakunen_zentai_jap_kukankiroku = (fields[17] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..time_zentai_jap_kojinkiroku = (fields[18] as List)
          .map((dynamic e) => (e as List).cast<double>())
          .toList()
      ..year_zentai_jap_kojinkiroku = (fields[19] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..month_zentai_jap_kojinkiroku = (fields[20] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..univname_zentai_jap_kojinkiroku = (fields[21] as List)
          .map((dynamic e) => (e as List).cast<String>())
          .toList()
      ..name_zentai_jap_kojinkiroku = (fields[22] as List)
          .map((dynamic e) => (e as List).cast<String>())
          .toList()
      ..gakunen_zentai_jap_kojinkiroku = (fields[23] as List)
          .map((dynamic e) => (e as List).cast<int>())
          .toList()
      ..time_univ_ryuugakusei_kukankiroku = (fields[24] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<double>())
                  .toList())
              .toList())
          .toList()
      ..year_univ_ryuugakusei_kukankiroku = (fields[25] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..month_univ_ryuugakusei_kukankiroku = (fields[26] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..name_univ_ryuugakusei_kukankiroku = (fields[27] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<String>())
                  .toList())
              .toList())
          .toList()
      ..gakunen_univ_ryuugakusei_kukankiroku = (fields[28] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..time_univ_ryuugakusei_kojinkiroku = (fields[29] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<double>())
              .toList())
          .toList()
      ..year_univ_ryuugakusei_kojinkiroku = (fields[30] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..month_univ_ryuugakusei_kojinkiroku = (fields[31] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..name_univ_ryuugakusei_kojinkiroku = (fields[32] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..gakunen_univ_ryuugakusei_kojinkiroku = (fields[33] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..time_univ_jap_kukankiroku = (fields[34] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<double>())
                  .toList())
              .toList())
          .toList()
      ..year_univ_jap_kukankiroku = (fields[35] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..month_univ_jap_kukankiroku = (fields[36] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..name_univ_jap_kukankiroku = (fields[37] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<String>())
                  .toList())
              .toList())
          .toList()
      ..gakunen_univ_jap_kukankiroku = (fields[38] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List)
                  .map((dynamic e) => (e as List).cast<int>())
                  .toList())
              .toList())
          .toList()
      ..time_univ_jap_kojinkiroku = (fields[39] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<double>())
              .toList())
          .toList()
      ..year_univ_jap_kojinkiroku = (fields[40] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..month_univ_jap_kojinkiroku = (fields[41] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList()
      ..name_univ_jap_kojinkiroku = (fields[42] as List)
          .map((dynamic e) => (e as List)
              .map((dynamic e) => (e as List).cast<String>())
              .toList())
          .toList()
      ..gakunen_univ_jap_kojinkiroku = (fields[43] as List)
          .map((dynamic e) =>
              (e as List).map((dynamic e) => (e as List).cast<int>()).toList())
          .toList();
  }

  @override
  void write(BinaryWriter writer, Kiroku obj) {
    writer
      ..writeByte(44)
      ..writeByte(0)
      ..write(obj.time_zentai_ryuugakusei_kukankiroku)
      ..writeByte(1)
      ..write(obj.year_zentai_ryuugakusei_kukankiroku)
      ..writeByte(2)
      ..write(obj.month_zentai_ryuugakusei_kukankiroku)
      ..writeByte(3)
      ..write(obj.univname_zentai_ryuugakusei_kukankiroku)
      ..writeByte(4)
      ..write(obj.name_zentai_ryuugakusei_kukankiroku)
      ..writeByte(5)
      ..write(obj.gakunen_zentai_ryuugakusei_kukankiroku)
      ..writeByte(6)
      ..write(obj.time_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(7)
      ..write(obj.year_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(8)
      ..write(obj.month_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(9)
      ..write(obj.univname_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(10)
      ..write(obj.name_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(11)
      ..write(obj.gakunen_zentai_ryuugakusei_kojinkiroku)
      ..writeByte(12)
      ..write(obj.time_zentai_jap_kukankiroku)
      ..writeByte(13)
      ..write(obj.year_zentai_jap_kukankiroku)
      ..writeByte(14)
      ..write(obj.month_zentai_jap_kukankiroku)
      ..writeByte(15)
      ..write(obj.univname_zentai_jap_kukankiroku)
      ..writeByte(16)
      ..write(obj.name_zentai_jap_kukankiroku)
      ..writeByte(17)
      ..write(obj.gakunen_zentai_jap_kukankiroku)
      ..writeByte(18)
      ..write(obj.time_zentai_jap_kojinkiroku)
      ..writeByte(19)
      ..write(obj.year_zentai_jap_kojinkiroku)
      ..writeByte(20)
      ..write(obj.month_zentai_jap_kojinkiroku)
      ..writeByte(21)
      ..write(obj.univname_zentai_jap_kojinkiroku)
      ..writeByte(22)
      ..write(obj.name_zentai_jap_kojinkiroku)
      ..writeByte(23)
      ..write(obj.gakunen_zentai_jap_kojinkiroku)
      ..writeByte(24)
      ..write(obj.time_univ_ryuugakusei_kukankiroku)
      ..writeByte(25)
      ..write(obj.year_univ_ryuugakusei_kukankiroku)
      ..writeByte(26)
      ..write(obj.month_univ_ryuugakusei_kukankiroku)
      ..writeByte(27)
      ..write(obj.name_univ_ryuugakusei_kukankiroku)
      ..writeByte(28)
      ..write(obj.gakunen_univ_ryuugakusei_kukankiroku)
      ..writeByte(29)
      ..write(obj.time_univ_ryuugakusei_kojinkiroku)
      ..writeByte(30)
      ..write(obj.year_univ_ryuugakusei_kojinkiroku)
      ..writeByte(31)
      ..write(obj.month_univ_ryuugakusei_kojinkiroku)
      ..writeByte(32)
      ..write(obj.name_univ_ryuugakusei_kojinkiroku)
      ..writeByte(33)
      ..write(obj.gakunen_univ_ryuugakusei_kojinkiroku)
      ..writeByte(34)
      ..write(obj.time_univ_jap_kukankiroku)
      ..writeByte(35)
      ..write(obj.year_univ_jap_kukankiroku)
      ..writeByte(36)
      ..write(obj.month_univ_jap_kukankiroku)
      ..writeByte(37)
      ..write(obj.name_univ_jap_kukankiroku)
      ..writeByte(38)
      ..write(obj.gakunen_univ_jap_kukankiroku)
      ..writeByte(39)
      ..write(obj.time_univ_jap_kojinkiroku)
      ..writeByte(40)
      ..write(obj.year_univ_jap_kojinkiroku)
      ..writeByte(41)
      ..write(obj.month_univ_jap_kojinkiroku)
      ..writeByte(42)
      ..write(obj.name_univ_jap_kojinkiroku)
      ..writeByte(43)
      ..write(obj.gakunen_univ_jap_kojinkiroku);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirokuAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
