import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:ekiden/ghensuu.dart';
import 'package:ekiden/senshu_data.dart';
import 'package:ekiden/univ_data.dart';
import 'package:ekiden/constants.dart';
import 'package:ekiden/kansuu/time_date.dart';
import 'package:ekiden/screens/Modal_senshu.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:screenshot/screenshot.dart';

class ModalKukanHaitiView extends StatefulWidget {
  final int targetUnivid;
  const ModalKukanHaitiView({super.key, required this.targetUnivid});

  @override
  State<ModalKukanHaitiView> createState() => _ModalKukanHaitiViewState();
}

class _ModalKukanHaitiViewState extends State<ModalKukanHaitiView> {
  final ScreenshotController _screenshotController = ScreenshotController();
  int? _selectedUnivId;
  bool _isExporting = false;

  String _formatDoubleToFixed(double value, int fractionDigits) {
    return value.toStringAsFixed(fractionDigits);
  }

  // 画像出力処理
  Future<void> _exportAsImage({required bool showDetail}) async {
    setState(() => _isExporting = true);
    try {
      final gBox = Hive.box<Ghensuu>('ghensuuBox');
      final sBox = Hive.box<SenshuData>('senshuBox');
      final uBox = Hive.box<UnivData>('univBox');

      final currentGhensuu = gBox.getAt(0)!;
      final univ = uBox.values.firstWhere((u) => u.id == _selectedUnivId);
      final raceIdx = currentGhensuu.hyojiracebangou;
      final kukanCount = currentGhensuu.kukansuu_taikaigoto[raceIdx];
      final allSenshus = sBox.values
          .where((s) => s.univid == _selectedUnivId)
          .toList();

      // レイアウト計算
      double canvasWidth = showDetail ? 1500.0 : 800.0;
      int itemsPerRow = showDetail ? 4 : 2;
      int rowCount = (kukanCount + itemsPerRow - 1) ~/ itemsPerRow;
      if (raceIdx == 3) {
        rowCount = (kukanCount * 2 + itemsPerRow - 1) ~/ itemsPerRow;
      }
      //double itemHeight = showDetail ? 650.0 : 100.0;
      double itemHeight = showDetail ? 420.0 : 70.0;
      double finalHeight = 150.0 + (rowCount * itemHeight) + 100.0;

      Widget captureWidget = Container(
        width: canvasWidth,
        height: finalHeight,
        padding: const EdgeInsets.all(40),
        color: HENSUU.backgroundcolor,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '${univ.name} - 区間配置 (${showDetail ? "詳細" : "標準"})',
              style: const TextStyle(
                color: Colors.white,
                fontSize: 32,
                fontWeight: FontWeight.bold,
                decoration: TextDecoration.none,
              ),
            ),
            const SizedBox(height: 10),
            Divider(color: Colors.white.withOpacity(0.5), thickness: 2),
            const SizedBox(height: 20),
            Expanded(
              child: Wrap(
                spacing: 20,
                runSpacing: 20,
                children: List.generate(kukanCount, (i) {
                  final targetSenshus = allSenshus
                      .where(
                        (s) => s.entrykukan_race[raceIdx][s.gakunen - 1] == i,
                      )
                      .toList();
                  if (targetSenshus.isEmpty) return const SizedBox.shrink();

                  return SizedBox(
                    //width: (canvasWidth - 120) / itemsPerRow,
                    width: 340,
                    child: Column(
                      children: targetSenshus
                          .map(
                            (s) => _buildSenshuPanelForImage(
                              currentGhensuu,
                              i,
                              s,
                              showDetail,
                            ),
                          )
                          .toList(),
                    ),
                  );
                }),
              ),
            ),
            const Align(
              alignment: Alignment.centerRight,
              child: Text(
                '----- Generated by 箱庭小駅伝SS -----',
                style: TextStyle(
                  color: Colors.grey,
                  fontSize: 16,
                  decoration: TextDecoration.none,
                ),
              ),
            ),
          ],
        ),
      );

      final image = await _screenshotController.captureFromWidget(
        MediaQuery(
          data: const MediaQueryData(textScaler: TextScaler.noScaling),
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: Material(child: captureWidget),
          ),
        ),
        targetSize: Size(canvasWidth, finalHeight),
      );

      final directory = await getTemporaryDirectory();
      final file = File('${directory.path}/kukan_haiti.png');
      await file.writeAsBytes(image!);
      await SharePlus.instance.share(
        ShareParams(files: [XFile(file.path)], text: '${univ.name} 区間配置'),
      );
    } catch (e) {
      debugPrint("Export Error: $e");
    } finally {
      setState(() => _isExporting = false);
    }
  }

  // 画像出力専用のパネル（ExpansionTileを使わずフラットに描画）
  Widget _buildSenshuPanelForImage(
    Ghensuu gh,
    int kukanIdx,
    SenshuData s,
    bool showDetail,
  ) {
    String kukanLabel = "${kukanIdx + 1}区";
    if (gh.hyojiracebangou == 3) kukanLabel = "${kukanIdx + 1}組";
    if (gh.hyojiracebangou == 4) kukanLabel = "記録会";

    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(15),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.1),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.white24),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text(
                kukanLabel,
                style: const TextStyle(
                  color: Colors.cyanAccent,
                  fontWeight: FontWeight.bold,
                  fontSize: 16,
                  decoration: TextDecoration.none,
                ),
              ),
              const SizedBox(width: 10),
              Text(
                s.name,
                style: const TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 18,
                  decoration: TextDecoration.none,
                ),
              ),
              //const Spacer(),
              Text(
                " (${s.gakunen}年)",
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 16,
                  decoration: TextDecoration.none,
                ),
              ),
            ],
          ),
          if (showDetail) ...[
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 8),
              child: Divider(color: Colors.white24),
            ),
            _buildNouryokuSection(gh, s),
            _buildRecordGrid(gh, s),
          ],
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final Box<Ghensuu> ghensuuBox = Hive.box<Ghensuu>('ghensuuBox');
    final Box<UnivData> univdataBox = Hive.box<UnivData>('univBox');
    final Box<SenshuData> senshudataBox = Hive.box<SenshuData>('senshuBox');

    return ValueListenableBuilder<Box<Ghensuu>>(
      valueListenable: ghensuuBox.listenable(),
      builder: (context, gBox, _) {
        final Ghensuu? currentGhensuu = gBox.getAt(0);
        if (currentGhensuu == null)
          return const Scaffold(body: Center(child: Text("データエラー")));

        if (_selectedUnivId == null) {
          _selectedUnivId = widget.targetUnivid;
        }

        final List<UnivData> allUnivs = univdataBox.values.toList()
          ..sort((a, b) => a.id.compareTo(b.id));
        bool selectedUnivIdEntryflag = false;
        if (allUnivs[_selectedUnivId!].taikaientryflag[currentGhensuu
                .hyojiracebangou] ==
            1) {
          selectedUnivIdEntryflag = true;
        }
        if (selectedUnivIdEntryflag == false) {
          for (int i = 0; i < allUnivs.length; i++) {
            if (allUnivs[i].taikaientryflag[currentGhensuu.hyojiracebangou] ==
                1) {
              _selectedUnivId = i;
              break;
            }
          }
        }

        return ValueListenableBuilder<Box<UnivData>>(
          valueListenable: univdataBox.listenable(),
          builder: (context, uBox, _) {
            final List<UnivData> entryUnivs =
                uBox.values
                    .where(
                      (u) =>
                          u.taikaientryflag[currentGhensuu.hyojiracebangou] ==
                          1,
                    )
                    .toList()
                  ..sort((a, b) => a.id.compareTo(b.id));

            return ValueListenableBuilder<Box<SenshuData>>(
              valueListenable: senshudataBox.listenable(),
              builder: (context, sBox, _) {
                final allSenshuData = sBox.values.toList();
                final displaySenshuData = allSenshuData
                    .where((s) => s.univid == _selectedUnivId)
                    .toList();

                if (currentGhensuu.hyojiracebangou == 4) {
                  displaySenshuData.sort((a, b) {
                    final int gakunenComp = b.gakunen.compareTo(a.gakunen);
                    return gakunenComp != 0
                        ? gakunenComp
                        : a.id.compareTo(b.id);
                  });
                }

                return Stack(
                  children: [
                    Scaffold(
                      backgroundColor: HENSUU.backgroundcolor,
                      appBar: AppBar(
                        title: const Text(
                          '区間配置確認',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                        backgroundColor: Colors.transparent,
                        elevation: 0,
                        centerTitle: true,
                        iconTheme: const IconThemeData(color: Colors.white),
                        actions: [
                          IconButton(
                            icon: const Icon(Icons.share),
                            onPressed: () => _showExportMenu(context),
                          ),
                        ],
                      ),
                      body: Column(
                        children: [
                          _buildUnivSelector(entryUnivs),
                          const Divider(color: Colors.white24, height: 1),
                          Expanded(
                            child: _buildMainList(
                              currentGhensuu,
                              displaySenshuData,
                            ),
                          ),
                          _buildBottomBar(context),
                        ],
                      ),
                    ),
                    if (_isExporting)
                      Container(
                        color: Colors.black54,
                        child: const Center(child: CircularProgressIndicator()),
                      ),
                  ],
                );
              },
            );
          },
        );
      },
    );
  }

  void _showExportMenu(BuildContext context) {
    final gBox = Hive.box<Ghensuu>('ghensuuBox');
    final currentGhensuu = gBox.getAt(0)!;
    final int raceIdx = currentGhensuu.hyojiracebangou;
    final int kukanCount = currentGhensuu.kukansuu_taikaigoto[raceIdx];

    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.grey[900],
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) => SafeArea(
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Padding(
                padding: EdgeInsets.all(20),
                child: Text(
                  "出力・共有メニュー",
                  style: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
              ),

              // --- 画像セクション ---
              _buildMenuTitle("画像(スクリーンショット) - 表示中の大学"),
              _buildMenuItem(
                context,
                Icons.image,
                "標準画像を保存",
                () => _exportAsImage(showDetail: false),
              ),
              _buildMenuItem(
                context,
                Icons.grid_view,
                "詳細画像を保存",
                () => _exportAsImage(showDetail: true),
              ),

              const Divider(color: Colors.white24),

              // --- 個別大学テキストセクション ---
              _buildMenuTitle("テキスト情報 - 表示中の大学"),
              _buildMenuItem(
                context,
                Icons.short_text,
                "超簡易版を共有 (名前のみ)",
                () => Share.share(_generateHaitiText(0)),
              ),
              _buildMenuItem(
                context,
                Icons.notes,
                "簡易版を共有 (主要記録)",
                () => Share.share(_generateHaitiText(1)),
              ),
              _buildMenuItem(
                context,
                Icons.content_copy,
                "詳細版をコピー (パネル全情報)",
                () {
                  Clipboard.setData(ClipboardData(text: _generateHaitiText(2)));
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text("詳細版をクリップボードにコピーしました")),
                  );
                },
              ),

              const Divider(color: Colors.white24),

              // --- 全大学一括セクション (ここを修正) ---
              _buildMenuTitle("全大学一括出力 - 区間を選択してコピー"),
              Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 10,
                ),
                child: Wrap(
                  spacing: 10, // ボタン間の横スペース
                  runSpacing: 10, // ボタン間の縦スペース
                  children: [
                    // 【追加】 全区間一括ボタン
                    ElevatedButton(
                      onPressed: () {
                        // 全区間分を生成してクリップボードにコピー
                        String text = _generateAllKukanList();
                        Clipboard.setData(ClipboardData(text: text));

                        Navigator.pop(context);
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(content: Text("全区間の全大学リストをコピーしました")),
                        );
                      },
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.orangeAccent.withOpacity(
                          0.2,
                        ), // 色を変えて目立たせる
                        foregroundColor: Colors.orangeAccent,
                        side: const BorderSide(color: Colors.orangeAccent),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                      ),
                      child: const Text("全区間 (一括)"),
                    ),

                    ...List.generate(kukanCount, (index) {
                      // ラベル生成 (例: 1区, 2組)
                      String label = "${index + 1}${raceIdx == 3 ? "組" : "区"}";
                      if (raceIdx == 4) label = "Rec"; // 記録会など

                      return ElevatedButton(
                        onPressed: () {
                          // 生成してクリップボードにコピー
                          String text = _generateSingleKukanList(index);
                          Clipboard.setData(ClipboardData(text: text));

                          // フィードバック表示
                          Navigator.pop(context); // メニューを閉じる
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text("$label の全大学リストをコピーしました")),
                          );
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.cyanAccent.withOpacity(0.2),
                          foregroundColor: Colors.cyanAccent,
                          side: const BorderSide(color: Colors.cyanAccent),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(20),
                          ),
                        ),
                        child: Text(label),
                      );
                    }),
                  ],
                ),
              ),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  // メニュー補助部品
  Widget _buildMenuTitle(String title) => Padding(
    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
    child: Align(
      alignment: Alignment.centerLeft,
      child: Text(
        title,
        style: const TextStyle(
          color: Colors.cyanAccent,
          fontSize: 12,
          fontWeight: FontWeight.bold,
        ),
      ),
    ),
  );

  Widget _buildMenuItem(
    BuildContext context,
    IconData icon,
    String label,
    VoidCallback onTap,
  ) => ListTile(
    leading: Icon(icon, color: Colors.white),
    title: Text(
      label,
      style: const TextStyle(color: Colors.white, fontSize: 14),
    ),
    onTap: () {
      Navigator.pop(context);
      onTap();
    },
  );
  // --- UI構成部品 (元のコードを維持) ---

  Widget _buildUnivSelector(List<UnivData> entryUnivs) {
    if (entryUnivs.isEmpty) return const SizedBox.shrink();
    final currentIndex = entryUnivs.indexWhere((u) => u.id == _selectedUnivId);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      child: Row(
        children: [
          IconButton(
            icon: const Icon(
              Icons.arrow_back_ios_new,
              color: Colors.cyanAccent,
              size: 20,
            ),
            onPressed: currentIndex > 0
                ? () => setState(
                    () => _selectedUnivId = entryUnivs[currentIndex - 1].id,
                  )
                : () => setState(
                    () =>
                        _selectedUnivId = entryUnivs[entryUnivs.length - 1].id,
                  ),
          ),
          Expanded(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.1),
                borderRadius: BorderRadius.circular(30),
                border: Border.all(color: Colors.white30),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<int>(
                  value: _selectedUnivId,
                  dropdownColor: Colors.grey[900],
                  isExpanded: true,
                  icon: const Icon(Icons.swap_vert, color: Colors.cyanAccent),
                  items: entryUnivs
                      .map(
                        (u) => DropdownMenuItem(
                          value: u.id,
                          child: Text(
                            u.name,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      )
                      .toList(),
                  onChanged: (val) => setState(() => _selectedUnivId = val),
                ),
              ),
            ),
          ),
          IconButton(
            icon: const Icon(
              Icons.arrow_forward_ios,
              color: Colors.cyanAccent,
              size: 20,
            ),
            onPressed: currentIndex < entryUnivs.length - 1
                ? () => setState(
                    () => _selectedUnivId = entryUnivs[currentIndex + 1].id,
                  )
                : () => setState(() => _selectedUnivId = entryUnivs[0].id),
          ),
        ],
      ),
    );
  }

  Widget _buildMainList(Ghensuu gh, List<SenshuData> senshus) {
    final int raceIdx = gh.hyojiracebangou;
    final int kukanCount = gh.kukansuu_taikaigoto[raceIdx];

    return ListView.builder(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      itemCount: kukanCount,
      itemBuilder: (context, i_kukan) {
        final targetSenshus = senshus
            .where((s) => s.entrykukan_race[raceIdx][s.gakunen - 1] == i_kukan)
            .toList();
        if (targetSenshus.isEmpty) return const SizedBox.shrink();
        return Column(
          children: targetSenshus
              .map((s) => _buildSenshuCard(gh, i_kukan, s))
              .toList(),
        );
      },
    );
  }

  Widget _buildSenshuCard(Ghensuu gh, int kukanIdx, SenshuData s) {
    String kukanLabel = "${kukanIdx + 1}区";
    if (gh.hyojiracebangou == 3) kukanLabel = "${kukanIdx + 1}組";
    if (gh.hyojiracebangou == 4) kukanLabel = "記録会";

    return Card(
      color: Colors.white.withOpacity(0.09),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
      margin: const EdgeInsets.only(bottom: 12),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          trailing: const SizedBox.shrink(),
          title: Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 4,
                ),
                decoration: BoxDecoration(
                  color: Colors.cyanAccent.withOpacity(0.25),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Text(
                  kukanLabel,
                  style: const TextStyle(
                    color: Colors.cyanAccent,
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  s.name,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 17,
                    fontWeight: FontWeight.bold,
                  ),
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              Text(
                "${s.gakunen}年",
                style: const TextStyle(color: Colors.white, fontSize: 14),
              ),
              TextButton(
                onPressed: () => _showSenshuDetail(context, s.id),
                child: Text(
                  '詳細',
                  style: TextStyle(color: HENSUU.LinkColor, fontSize: 15),
                ),
              ),
            ],
          ),
          subtitle: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                "${_formatDoubleToFixed(gh.kyori_taikai_kukangoto[gh.hyojiracebangou][kukanIdx], 0)}m",
                style: const TextStyle(color: Colors.white70, fontSize: 13),
              ),
              Container(
                height: 28,
                padding: const EdgeInsets.symmetric(horizontal: 12),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.white54),
                  borderRadius: BorderRadius.circular(14),
                ),
                child: const Center(
                  child: Text(
                    "表示 / 閉じる",
                    style: TextStyle(color: Colors.white, fontSize: 12),
                  ),
                ),
              ),
            ],
          ),
          childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
          children: [
            const Divider(color: Colors.white24),
            _buildNouryokuSection(gh, s),
            _buildRecordGrid(gh, s),
          ],
        ),
      ),
    );
  }

  void _showSenshuDetail(BuildContext context, int senshuId) {
    showGeneralDialog(
      context: context,
      barrierColor: Colors.black.withOpacity(0.8),
      barrierDismissible: true,
      barrierLabel: '詳細',
      transitionDuration: const Duration(milliseconds: 300),
      pageBuilder: (context, animation, secondaryAnimation) =>
          ModalSenshuDetailView(senshuId: senshuId),
      transitionBuilder: (context, animation, secondaryAnimation, child) =>
          FadeTransition(
            opacity: CurvedAnimation(parent: animation, curve: Curves.easeOut),
            child: child,
          ),
    );
  }

  Widget _buildNouryokuSection(Ghensuu gh, SenshuData s) {
    //過去に同じ区間を走ったことがあるかどうかの表示
    int keikenkaisuu = 0;
    for (int i_gakunen = 0; i_gakunen < s.gakunen - 1; i_gakunen++) {
      if (s.entrykukan_race[gh.hyojiracebangou][i_gakunen] ==
          s.entrykukan_race[gh.hyojiracebangou][s.gakunen - 1]) {
        keikenkaisuu++;
      }
    }
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Wrap(
        spacing: 12, // アイテム間の横の隙間
        runSpacing: 8, // 折り返した時の行間の隙間
        children: [
          _nouryokuItem(
            "駅伝男",
            gh.nouryokumieruflag[0] == 1 ? "${s.konjou}" : "??",
          ),
          _nouryokuItem(
            "平常心",
            gh.nouryokumieruflag[1] == 1 ? "${s.heijousin}" : "??",
          ),
          _nouryokuItem("調子", "${s.chousi}"),
          if (keikenkaisuu > 0) _nouryokuItem("この区間の経験回数", "$keikenkaisuu"),
        ],
      ),
    );
  }

  // --- 各アイテムの定義 ---
  Widget _nouryokuItem(String label, String value) {
    // アイテム内も Row ではなく Wrap にすることで、
    // 「ラベル名：値」が1行に収まらないほど長い場合にも対応できます
    return Wrap(
      crossAxisAlignment: WrapCrossAlignment.center,
      children: [
        Text(
          "$label ",
          style: const TextStyle(
            color: Colors.white70,
            fontSize: 13,
            decoration: TextDecoration.none,
          ),
        ),
        Text(
          value,
          style: const TextStyle(
            color: Colors.orangeAccent,
            fontWeight: FontWeight.bold,
            fontSize: 14,
            decoration: TextDecoration.none,
          ),
        ),
      ],
    );
  }

  Widget _buildRecordGrid(Ghensuu gh, SenshuData s) {
    List<Map<String, dynamic>> records = [
      if (gh.hyojiracebangou != 4)
        {'label': '5千best', 'idx': 0, 'showRank': true},
      {'label': '1万', 'idx': 1, 'showRank': true},
      {'label': 'ハーフ', 'idx': 2, 'showRank': true},
      if (gh.hyojiracebangou != 4)
        {'label': '登り1万', 'idx': 4, 'showRank': false},
      if (gh.hyojiracebangou != 4)
        {'label': '下り1万', 'idx': 5, 'showRank': false},
      {'label': 'ロード1万', 'idx': 6, 'showRank': false},
      if (gh.hyojiracebangou != 4)
        {'label': 'クロカン1万', 'idx': 7, 'showRank': false},
    ];
    return Column(
      children: records
          .map((r) => _buildRecordRow(s, r['label'], r['idx'], r['showRank']))
          .toList(),
    );
  }

  Widget _buildRecordRow(SenshuData s, String label, int idx, bool showRank) {
    final bool hasRecord = s.time_bestkiroku[idx] != TEISUU.DEFAULTTIME;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 85,
            child: Text(
              label,
              style: const TextStyle(
                color: Colors.white70,
                fontSize: 13,
                decoration: TextDecoration.none,
              ),
            ),
          ),
          if (!hasRecord)
            const Text(
              "記録無",
              style: TextStyle(
                color: Colors.white38,
                fontSize: 13,
                decoration: TextDecoration.none,
              ),
            )
          else ...[
            Text(
              TimeDate.timeToFunByouString(s.time_bestkiroku[idx]),
              style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
                fontSize: 14,
                decoration: TextDecoration.none,
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Wrap(
                alignment: WrapAlignment.end,
                spacing: 4,
                runSpacing: 4,
                children: [
                  if (showRank) ...[
                    _rankTag("区", s.kukannaijuni[idx] + 1),
                    _rankTag("学", s.gakunaijuni_bestkiroku[idx] + 1),
                    _rankTag("全", s.zentaijuni_bestkiroku[idx] + 1),
                  ] else ...[
                    _rankTag("学", s.gakunaijuni_bestkiroku[idx] + 1),
                  ],
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  Widget _rankTag(String label, int rank) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.white30),
        borderRadius: BorderRadius.circular(5),
        color: Colors.white.withOpacity(0.05),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            label,
            style: const TextStyle(
              color: Colors.cyanAccent,
              fontSize: 11,
              fontWeight: FontWeight.bold,
              decoration: TextDecoration.none,
            ),
          ),
          const SizedBox(width: 2),
          Text(
            "$rank",
            style: const TextStyle(
              color: Colors.white,
              fontSize: 13,
              fontWeight: FontWeight.bold,
              decoration: TextDecoration.none,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomBar(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: HENSUU.backgroundcolor,
        boxShadow: [
          BoxShadow(
            color: Colors.black54,
            blurRadius: 10,
            offset: Offset(0, -2),
          ),
        ],
      ),
      child: ElevatedButton(
        onPressed: () => Navigator.pop(context),
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.blueAccent,
          foregroundColor: Colors.white,
          minimumSize: const Size(double.infinity, 54),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          elevation: 5,
        ),
        child: const Text(
          "戻る",
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
      ),
    );
  }

  // 【追加】全区間のリストを一括生成するメソッド
  String _generateAllKukanList() {
    final gBox = Hive.box<Ghensuu>('ghensuuBox');
    final currentGhensuu = gBox.getAt(0)!;
    final int raceIdx = currentGhensuu.hyojiracebangou;
    final int kukanCount = currentGhensuu.kukansuu_taikaigoto[raceIdx];

    StringBuffer sb = StringBuffer();
    sb.writeln("=== 全区間・全大学詳細リスト ===");
    sb.writeln("-----------------------------------\n");

    for (int i = 0; i < kukanCount; i++) {
      // 既存の単一区間生成ロジックを再利用
      sb.write(_generateSingleKukanList(i));
      sb.writeln("\n"); // 区間ごとに改行を入れる
    }

    return sb.toString();
  }

  // 改修後: 指定された区間の全大学選手リスト（詳細版フォーマット）
  String _generateSingleKukanList(int targetKukanIdx) {
    final gBox = Hive.box<Ghensuu>('ghensuuBox');
    final sBox = Hive.box<SenshuData>('senshuBox');
    final uBox = Hive.box<UnivData>('univBox');

    final currentGhensuu = gBox.getAt(0)!;
    final raceIdx = currentGhensuu.hyojiracebangou;

    // 区間名の決定
    String kukanLabel = "${targetKukanIdx + 1}${raceIdx == 3 ? "組" : "区"}";
    if (raceIdx == 4) kukanLabel = "記録会";

    // エントリー済み大学を取得してID順にソート
    final entryUnivs =
        uBox.values.where((u) => u.taikaientryflag[raceIdx] == 1).toList()
          ..sort((a, b) => a.id.compareTo(b.id)); // 大学ID順

    StringBuffer sb = StringBuffer();
    String kyoristring =
        "${_formatDoubleToFixed(currentGhensuu.kyori_taikai_kukangoto[raceIdx][targetKukanIdx], 0)}m";

    sb.writeln("=== $kukanLabel($kyoristring) 全大学詳細リスト ===");
    //sb.writeln("生成日時: ${DateTime.now().toString()}");
    sb.writeln("");

    bool hasEntry = false;

    // 大学ID順にループ
    for (var univ in entryUnivs) {
      // その大学の選手の中で、指定区間にエントリーしている選手を探す
      final targetSenshus = sBox.values.where((s) {
        return s.univid == univ.id &&
            s.entrykukan_race[raceIdx][s.gakunen - 1] == targetKukanIdx;
      }).toList();

      if (targetSenshus.isNotEmpty) {
        hasEntry = true;
        for (var s in targetSenshus) {
          // --- ここから詳細版(mode=2)のロジックを適用 ---

          // ヘッダー: 【大学名】 区間 選手名 (学年)
          //sb.writeln('【${univ.name}】 $kukanLabel ${s.name} (${s.gakunen}年)');
          sb.writeln('【${univ.name}】  ${s.name} (${s.gakunen}年)');

          // 距離表示 (駅伝の場合のみ)
          /*if (raceIdx != 3 && raceIdx != 4) {
            sb.writeln(
              ' ${_formatDoubleToFixed(currentGhensuu.kyori_taikai_kukangoto[raceIdx][targetKukanIdx], 0)}m',
            );
          }*/

          // 能力値 (フラグチェック付き)
          sb.write(
            '  駅伝男:${currentGhensuu.nouryokumieruflag[0] == 1 ? s.konjou : "??"} ',
          );
          sb.write(
            '平常心:${currentGhensuu.nouryokumieruflag[1] == 1 ? s.heijousin : "??"} ',
          );
          sb.writeln('調子:${s.chousi}');

          //過去に同じ区間を走ったことがあるかどうかの表示
          int keikenkaisuu = 0;
          for (int i_gakunen = 0; i_gakunen < s.gakunen - 1; i_gakunen++) {
            if (s.entrykukan_race[currentGhensuu.hyojiracebangou][i_gakunen] ==
                s.entrykukan_race[currentGhensuu.hyojiracebangou][s.gakunen -
                    1]) {
              keikenkaisuu++;
            }
          }
          //if (keikenkaisuu > 0) {
          sb.writeln('  この区間の経験回数:$keikenkaisuu回');
          //}

          // 記録情報の生成用ローカル関数 (詳細版固定)
          String getRec(int idx, bool showRank) {
            if (s.time_bestkiroku[idx] == TEISUU.DEFAULTTIME) return "記録無";
            String base = TimeDate.timeToFunByouString(s.time_bestkiroku[idx]);

            // 詳細版なので順位情報を付与
            if (showRank) {
              // 区間順位・学内順位・全体順位
              base +=
                  " [区:${s.kukannaijuni[idx] + 1}位 学:${s.gakunaijuni_bestkiroku[idx] + 1}位 全:${s.zentaijuni_bestkiroku[idx] + 1}位]";
            } else {
              // 学内順位のみ
              base += " [学:${s.gakunaijuni_bestkiroku[idx] + 1}位]";
            }
            return base;
          }

          // 主要記録
          sb.writeln('  5000m: ${getRec(0, true)}');
          sb.writeln('  10000m: ${getRec(1, true)}');
          sb.writeln('  ハーフ: ${getRec(2, true)}');

          // 詳細記録 (登り・下り・ロード・クロカン)
          sb.writeln('  登り1万: ${getRec(4, false)}');
          sb.writeln('  下り1万: ${getRec(5, false)}');
          sb.writeln('  ロード1万: ${getRec(6, false)}');
          sb.writeln('  クロカン1万: ${getRec(7, false)}');

          sb.writeln("-----------------------------------"); // 区切り線
        }
      }
    }

    sb.writeln(
      "\n※「区」はその区間にエントリーされている選手の中でのその種目の持ちタイムの順位、「学」はその種目の所属大学学内での持ちタイムの順位、「全」はその種目の学生全体での持ちタイムの順位",
    );

    if (!hasEntry) {
      sb.writeln("この区間へのエントリーはありません。");
    }

    return sb.toString();
  }

  // --- テキスト情報生成ロジック (3段階) ---
  String _generateHaitiText(int mode) {
    final gBox = Hive.box<Ghensuu>('ghensuuBox');
    final sBox = Hive.box<SenshuData>('senshuBox');
    final uBox = Hive.box<UnivData>('univBox');

    final currentGhensuu = gBox.getAt(0)!;
    final univ = uBox.values.firstWhere((u) => u.id == _selectedUnivId);
    final raceIdx = currentGhensuu.hyojiracebangou;
    final kukanCount = currentGhensuu.kukansuu_taikaigoto[raceIdx];
    final allSenshus = sBox.values
        .where((s) => s.univid == _selectedUnivId)
        .toList();

    String modeName = mode == 2 ? "詳細版" : (mode == 1 ? "簡易版" : "超簡易版");
    StringBuffer sb = StringBuffer();
    sb.writeln('【${univ.name}】区間配置 ($modeName)');
    sb.writeln('-----------------------------------');

    for (int i = 0; i < kukanCount; i++) {
      final target = allSenshus
          .where((s) => s.entrykukan_race[raceIdx][s.gakunen - 1] == i)
          .toList();
      for (var s in target) {
        String kukanLabel = "${i + 1}${raceIdx == 3 ? "組" : "区"}";
        if (raceIdx == 4) kukanLabel = "正月駅伝予選";

        sb.writeln('$kukanLabel ${s.name} (${s.gakunen}年)');
        if (raceIdx != 3 && raceIdx != 4) {
          sb.writeln(
            ' ${_formatDoubleToFixed(currentGhensuu.kyori_taikai_kukangoto[currentGhensuu.hyojiracebangou][i], 0)}m',
          );
        }

        // --- 簡易版以上 (mode 1 or 2) ---
        if (mode >= 1) {
          // 能力値
          sb.write(
            '  駅伝男:${currentGhensuu.nouryokumieruflag[0] == 1 ? s.konjou : "??"} ',
          );
          sb.write(
            '平常心:${currentGhensuu.nouryokumieruflag[1] == 1 ? s.heijousin : "??"} ',
          );
          sb.writeln('調子:${s.chousi}');

          //過去に同じ区間を走ったことがあるかどうかの表示
          int keikenkaisuu = 0;
          for (int i_gakunen = 0; i_gakunen < s.gakunen - 1; i_gakunen++) {
            if (s.entrykukan_race[currentGhensuu.hyojiracebangou][i_gakunen] ==
                s.entrykukan_race[currentGhensuu.hyojiracebangou][s.gakunen -
                    1]) {
              keikenkaisuu++;
            }
          }
          //if (keikenkaisuu > 0) {
          sb.writeln('  この区間の経験回数:$keikenkaisuu回');
          //}

          // 記録情報の生成用サブ関数
          String getRec(int idx, bool showRank) {
            if (s.time_bestkiroku[idx] == TEISUU.DEFAULTTIME) return "記録無";
            String base = TimeDate.timeToFunByouString(s.time_bestkiroku[idx]);
            if (mode == 2) {
              // 詳細版は順位を全て盛り込む
              if (showRank) {
                base +=
                    " [区:${s.kukannaijuni[idx] + 1}位 学:${s.gakunaijuni_bestkiroku[idx] + 1}位 全:${s.zentaijuni_bestkiroku[idx] + 1}位]";
              } else {
                base += " [学:${s.gakunaijuni_bestkiroku[idx] + 1}位]";
              }
            }
            return base;
          }

          sb.writeln('  5000m: ${getRec(0, true)}');
          sb.writeln('  10000m: ${getRec(1, true)}');
          sb.writeln('  ハーフ: ${getRec(2, true)}');

          // --- 詳細版 (mode 2) のみの追加情報 ---
          if (mode == 2) {
            sb.writeln('  登り1万: ${getRec(4, false)}');
            sb.writeln('  下り1万: ${getRec(5, false)}');
            sb.writeln('  ロード1万: ${getRec(6, false)}');
            sb.writeln('  クロカン1万: ${getRec(7, false)}');
          }
        }
        sb.writeln('');
      }
    }
    if (mode == 2) {
      sb.writeln(
        "\n※「区」はその区間にエントリーされている選手の中でのその種目の持ちタイムの順位、「学」はその種目の所属大学学内での持ちタイムの順位、「全」はその種目の学生全体での持ちタイムの順位",
      );
    }

    return sb.toString();
  }
}
